services:
  jenkins:
    build: .
    image: my-jenkins:latest
    container_name: my_jenkins
    restart: unless-stopped
    environment:
      - ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
      - DEVELOPER_PASSWORD=${JENKINS_DEVELOPER_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - my_jenkins_network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-tunnel
    restart: unless-stopped
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml:ro # Montage crucial pour que ngrok trouve le fichier
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - ALLOWED_EMAILS=${NGROK_ALLOWED_EMAILS}
    command:
      - "start"
      - "jenkins"
      - "--config=/etc/ngrok.yml"
    depends_on:
      - jenkins
    networks:
      - my_jenkins_network

    #     ngrok:
    # image: ngrok/ngrok:latest
    # environment:
    #   - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    #   - ALLOWED_EMAILS=${NGROK_ALLOWED_EMAILS}
    # volumes:
    #   - ./ngrok.yml:/etc/ngrok.yml:ro
    # command:
    #   - "http"
    #   - "--url=unmundane-nonarchitectural-vina.ngrok-free.dev"
    #   - "--config=/etc/ngrok.yml"
    #   - "jenkins:8080"

networks:
  my_jenkins_network:
    driver: bridge